export const BASE_URL = 'https://api.themoviedb.org/3/';

export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0MzBjZTM5ZGRiYjZkNzY3NjY0ZjVhYjFkOWQ1MzY0NSIsInN1YiI6IjYzNjU2MzY5YzRmNTUyMDA3YzNhYjNlMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Pn4sjsSaZhCmza9wnfgKUN77mmluaZEobMoRdTPrhpg";